services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
  postgres:
    image: "postgres:alpine3.19"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}

